jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Build the Docker image
      run: mvn clean package -Pdev -DskipTests -U -e && /bin/cp -rf powerjob-server/powerjob-server-starter/target/*.jar
        powerjob-server/docker/powerjob-server.jar && /bin/cp -rf powerjob-worker-agent/target/*.jar
        powerjob-worker-agent/powerjob-agent.jar && /bin/cp -rf powerjob-worker-samples/target/*.jar
        powerjob-worker-samples/powerjob-worker-samples.jar
    - continue-on-error: true
      uses: docker/build-push-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: powerjob-server/docker/
        push: false
        repository: tjqq/powerjob-server
        tag_with_ref: true
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      uses: docker/build-push-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: powerjob-worker-agent/
        push: false
        repository: tjqq/powerjob-agent
        tag_with_ref: true
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      uses: docker/build-push-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: powerjob-worker-samples/
        push: false
        repository: tjqq/powerjob-worker-samples
        tag_with_ref: true
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
name: Docker Image CI
on:
  repository_dispatch:
    types: trigger-ga___docker-image.yml
