jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B clean package -Pdev -DskipTests --file pom.xml
    - continue-on-error: true
      name: upload build result
      run: mkdir staging && cp powerjob-server/powerjob-server-starter/target/*.jar
        staging/powerjob-server.jar && cp powerjob-client/target/*.jar staging/powerjob-client.jar
        && cp powerjob-worker-agent/target/*.jar staging/powerjob-agent.jar
    - continue-on-error: true
      uses: actions/upload-artifact@v1
      with:
        name: powerjob-server.jar
        path: staging/powerjob-server.jar
    - continue-on-error: true
      uses: actions/upload-artifact@v1
      with:
        name: powerjob-client.jar
        path: staging/powerjob-client.jar
    - continue-on-error: true
      uses: actions/upload-artifact@v1
      with:
        name: powerjob-agent.jar
        path: staging/powerjob-agent.jar
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
